import {
  HeadingBlock,
  TextBlock,
  ButtonBlock,
  ImageBlock,
  SpacerBlock,
  VideoBlock,
  CollectionBlock,
  CollectionItemBlock,
  ProductBlock,
  ProductListBlock,
  ProductGridItemsBlock,
  LinkListBlock,
  SocialLinksBlock,
  IconBlock,
  ContactFormBlock,
  EmailSignupBlock,
  AccordionBlock,
  CardBlock,
  MenuBlock,
  AnnouncementBlock,
  DividerBlock,
  ProductImagesBlock,
  ProductTitleBlock,
  ProductPriceBlock,
  ProductVariantsBlock,
  AddToCartBlock,
  ProductDescriptionBlock,
  CollectionHeadingBlock,
  CollectionDescriptionBlock,
  ProductGridBlock,
  CartItemsBlock,
  CartSummaryBlock,
  CheckoutPageTitleBlock,
  CheckoutFormBlock,
  ThankYouIconBlock,
  ThankYouHeaderBlock,
  OrderDetailsBlock,
  PaymentInstructionsBlock,
  GiftCardCodesBlock,
  ContinueShoppingBlock,
} from './StandardBlocks';

import {
  BaseHeadingSchema,
  BaseTextSchema,
  BaseButtonSchema,
  BaseImageSchema,
  BaseVideoSchema,
  BaseSpacerSchema,
  BaseCollectionSchema,
  BaseCollectionItemSchema,
  BaseProductSchema,
  BaseProductListSchema,
  BaseLinkListSchema,
  BaseSocialLinkSchema,
  BaseIconSchema,
  BaseContactFormSchema,
  BaseEmailSignupSchema,
  BaseAccordionSchema,
  BaseCardSchema,
  BaseMenuSchema,
  BaseAnnouncementSchema,
  BaseDividerSchema,
  BaseProductImagesSchema,
  BaseProductTitleSchema,
  BaseProductPriceSchema,
  BaseProductVariantsSchema,
  BaseAddToCartSchema,
  BaseProductDescriptionSchema,
} from './schemas';

export const primeBlockRegistry: Record<string, { component: any; schema: any }> = {
  heading:                { component: HeadingBlock as any, schema: BaseHeadingSchema },
  text:                   { component: TextBlock as any, schema: BaseTextSchema },
  button:                 { component: ButtonBlock as any, schema: BaseButtonSchema },
  image:                  { component: ImageBlock as any, schema: BaseImageSchema },
  video:                  { component: VideoBlock as any, schema: BaseVideoSchema },
  spacer:                 { component: SpacerBlock as any, schema: BaseSpacerSchema },
  collection:             { component: CollectionBlock as any, schema: BaseCollectionSchema },
  collection_item:        { component: CollectionItemBlock as any, schema: BaseCollectionItemSchema },
  product:                { component: ProductBlock as any, schema: BaseProductSchema },
  product_list:           { component: ProductListBlock as any, schema: BaseProductListSchema },
  product_grid_items:     { component: ProductGridItemsBlock as any, schema: BaseProductListSchema },
  link_list:              { component: LinkListBlock as any, schema: BaseLinkListSchema },
  social_link:            { component: SocialLinksBlock as any, schema: BaseSocialLinkSchema },
  icon:                   { component: IconBlock as any, schema: BaseIconSchema },
  contact_form:           { component: ContactFormBlock as any, schema: BaseContactFormSchema },
  email_signup:           { component: EmailSignupBlock as any, schema: BaseEmailSignupSchema },
  accordion:              { component: AccordionBlock as any, schema: BaseAccordionSchema },
  card:                   { component: CardBlock as any, schema: BaseCardSchema },
  menu:                   { component: MenuBlock as any, schema: BaseMenuSchema },
  announcement:           { component: AnnouncementBlock as any, schema: BaseAnnouncementSchema },
  divider:                { component: DividerBlock as any, schema: BaseDividerSchema },
  product_images:         { component: ProductImagesBlock as any, schema: BaseProductImagesSchema },
  product_title:          { component: ProductTitleBlock as any, schema: BaseProductTitleSchema },
  product_price:          { component: ProductPriceBlock as any, schema: BaseProductPriceSchema },
  product_variants:       { component: ProductVariantsBlock as any, schema: BaseProductVariantsSchema },
  add_to_cart:            { component: AddToCartBlock as any, schema: BaseAddToCartSchema },
  product_description:    { component: ProductDescriptionBlock as any, schema: BaseProductDescriptionSchema },
  collection_heading:     { component: CollectionHeadingBlock as any, schema: BaseHeadingSchema },
  collection_description: { component: CollectionDescriptionBlock as any, schema: BaseTextSchema },
  product_grid:           { component: ProductGridBlock as any, schema: BaseProductListSchema },
  cart_items:             { component: CartItemsBlock as any, schema: BaseHeadingSchema },
  cart_summary:           { component: CartSummaryBlock as any, schema: BaseHeadingSchema },
  checkout_page_title:    { component: CheckoutPageTitleBlock as any, schema: BaseHeadingSchema },
  checkout_form:          { component: CheckoutFormBlock as any, schema: BaseHeadingSchema },
  thank_you_icon:         { component: ThankYouIconBlock as any, schema: BaseHeadingSchema },
  thank_you_header:       { component: ThankYouHeaderBlock as any, schema: BaseHeadingSchema },
  order_details:          { component: OrderDetailsBlock as any, schema: BaseHeadingSchema },
  payment_instructions:   { component: PaymentInstructionsBlock as any, schema: BaseHeadingSchema },
  gift_card_codes:        { component: GiftCardCodesBlock as any, schema: BaseHeadingSchema },
  continue_shopping:      { component: ContinueShoppingBlock as any, schema: BaseHeadingSchema },
};
